var data = {
    "user_tags":{
        "cityLevel":[
            {
                "name":"未知",
                "id":-1,
                "selected":false
            },
            {
                "name":"一线城市",
                "id":1,
                "selected":false
            },
            {
                "name":"新一线城市",
                "id":2,
                "selected":false
            },
            {
                "name":"二线城市",
                "id":3,
                "selected":false
            },
            {
                "name":"三线城市",
                "id":4,
                "selected":false
            },
            {
                "name":"四线城市",
                "id":5,
                "selected":false
            },
            {
                "name":"五线城市",
                "id":6,
                "selected":false
            }
        ],
        "cityRegion":[
            {
                "name":"未知",
                "id":-1,
                "selected":false
            },
            {
                "name":"华南地区",
                "id":248,
                "selected":false
            },
            {
                "name":"华北地区",
                "id":249,
                "selected":false
            },
            {
                "name":"华东地区",
                "id":250,
                "selected":false
            },
            {
                "name":"直辖市地区",
                "id":251,
                "selected":false
            },
            {
                "name":"西南地区",
                "id":252,
                "selected":false
            },
            {
                "name":"东北地区",
                "id":253,
                "selected":false
            },
            {
                "name":"港澳台地区",
                "id":254,
                "selected":false
            },
            {
                "name":"西北地区",
                "id":255,
                "selected":false
            },
            {
                "name":"华中地区",
                "id":256,
                "selected":false
            }
        ],
        "province":[
            {
                "name":"北京市",
                "id":257,
                "selected":false
            },
            {
                "name":"上海市",
                "id":258,
                "selected":false
            },
            {
                "name":"天津市",
                "id":259,
                "selected":false
            },
            {
                "name":"重庆市",
                "id":260,
                "selected":false
            },
            {
                "name":"内蒙古自治区",
                "id":261,
                "selected":false
            },
            {
                "name":"河北省",
                "id":262,
                "selected":false
            },
            {
                "name":"江西省",
                "id":263,
                "selected":false
            },
            {
                "name":"山东省",
                "id":264,
                "selected":false
            },
            {
                "name":"山西省",
                "id":265,
                "selected":false
            },
            {
                "name":"河南省",
                "id":266,
                "selected":false
            },
            {
                "name":"辽宁省",
                "id":267,
                "selected":false
            },
            {
                "name":"湖北省",
                "id":268,
                "selected":false
            },
            {
                "name":"吉林省",
                "id":269,
                "selected":false
            },
            {
                "name":"湖南省",
                "id":270,
                "selected":false
            },
            {
                "name":"广东省",
                "id":271,
                "selected":false
            },
            {
                "name":"江苏省",
                "id":272,
                "selected":false
            },
            {
                "name":"广西壮族自治区",
                "id":273,
                "selected":false
            },
            {
                "name":"海南省",
                "id":274,
                "selected":false
            },
            {
                "name":"四川省",
                "id":275,
                "selected":false
            },
            {
                "name":"浙江省",
                "id":276,
                "selected":false
            },
            {
                "name":"贵州省",
                "id":277,
                "selected":false
            },
            {
                "name":"安徽省",
                "id":278,
                "selected":false
            },
            {
                "name":"云南省",
                "id":279,
                "selected":false
            },
            {
                "name":"福建省",
                "id":280,
                "selected":false
            },
            {
                "name":"陕西省",
                "id":281,
                "selected":false
            },
            {
                "name":"西藏自治区",
                "id":282,
                "selected":false
            },
            {
                "name":"甘肃省",
                "id":283,
                "selected":false
            },
            {
                "name":"青海省",
                "id":284,
                "selected":false
            },
            {
                "name":"宁夏回族自治区",
                "id":285,
                "selected":false
            },
            {
                "name":"台湾",
                "id":286,
                "selected":false
            },
            {
                "name":"黑龙江省",
                "id":320,
                "selected":false
            },
            {
                "name":"新疆维吾尔自治区",
                "id":386,
                "selected":false
            }
        ],
        "nameValidation":[
            {
                "name":"姓名为空",
                "id":0,
                "selected":false
            },
            {
                "name":"姓名不为空",
                "id":1,
                "selected":false
            }
        ],
        "sex":[
            {
                "name":"男",
                "id":1,
                "selected":false
            },
            {
                "name":"女",
                "id":0,
                "selected":false
            },
            {
                "name":"未识别",
                "id":-1,
                "selected":false
            }
        ],
        "age":[
            {
                "name":"未知用户",
                "id":-1,
                "selected":false
            },
            {
                "name":"50前",
                "id":1,
                "selected":false
            },
            {
                "name":"50后",
                "id":2,
                "selected":false
            },
            {
                "name":"60后",
                "id":3,
                "selected":false
            },
            {
                "name":"70后",
                "id":4,
                "selected":false
            }
        ]
    },
    "user_dragoncard_tags":{
        "institutionType":[
            {
                "name":"银行",
                "id":1,
                "selected":false
            },
            {
                "name":"旅游",
                "id":2,
                "selected":false
            },
            {
                "name":"保险",
                "id":3,
                "selected":false
            },
            {
                "name":"航空公司",
                "id":4,
                "selected":false
            },
            {
                "name":"广告",
                "id":5,
                "selected":false
            },
            {
                "name":"企业",
                "id":6,
                "selected":false
            },
            {
                "name":"酒店",
                "id":7,
                "selected":false
            },
            {
                "name":"外贸",
                "id":8,
                "selected":false
            },
            {
                "name":"理财",
                "id":9,
                "selected":false
            },
            {
                "name":"其他",
                "id":10,
                "selected":false
            }
        ],
        "protocolType":[
            {
                "name":"冠名领导",
                "id":1,
                "selected":false
            },{
                "name":"冠名持卡",
                "id":2,
                "selected":false
            },{
                "name":"服务会员",
                "id":3,
                "selected":false
            },{
                "name":"地方政要",
                "id":4,
                "selected":false
            },{
                "name":"机场内接",
                "id":5,
                "selected":false
            },{
                "name":"VVIP",
                "id":6,
                "selected":false
            },{
                "name":"包量客户",
                "id":7,
                "selected":false
            },{
                "name":"结算会员",
                "id":8,
                "selected":false
            },{
                "name":"结算金银卡",
                "id":9,
                "selected":false
            },{
                "name":"结算头等舱",
                "id":10,
                "selected":false
            },{
                "name":"零散散客",
                "id":11,
                "selected":false
            },{
                "name":"百事特内接",
                "id":12,
                "selected":false
            }
        ],
        "productType":[
            {
                "name":"两舱休息室",
                "id":1,
                "selected":false
            },{
                "name":"VIP接送机",
                "id":2,
                "selected":false
            },{
                "name":"异地贵宾服务",
                "id":3,
                "selected":false
            },{
                "name":"独立安检通道",
                "id":4,
                "selected":false
            },
        ]
    },
    "app_feature_tags":{
        "lounge_type":[
            {
                "name":"建行厅",
                "id":1,
                "selected":false
            },{
                "name":"龙腾厅",
                "id":2,
                "selected":false
            },{
                "name":"头等舱",
                "id":3,
                "selected":false
            }
        ],
        "accumulationUsage":[
            {
                "name":"未知",
                "id":1,
                "selected":false
            },{
                "name":"0次",
                "id":2,
                "selected":false
            },{
                "name":"1次",
                "id":3,
                "selected":false
            },{
                "name":"2次",
                "id":4,
                "selected":false
            },{
                "name":"3次",
                "id":5,
                "selected":false
            },{
                "name":"4次",
                "id":6,
                "selected":false
            },{
                "name":"5次",
                "id":7,
                "selected":false
            },{
                "name":"6-9次",
                "id":8,
                "selected":false
            },{
                "name":"10-19次",
                "id":9,
                "selected":false
            },{
                "name":"20-29次",
                "id":10,
                "selected":false
            },{
                "name":"30次及以上",
                "id":11,
                "selected":false
            }
        ],
        "recencyUsage":[
            {
                "name":"当月",
                "id":1,
                "selected":false
            },{
                "name":"近三个月",
                "id":2,
                "selected":false
            },{
                "name":"近半年",
                "id":3,
                "selected":false
            },{
                "name":"近一年",
                "id":4,
                "selected":false
            },{
                "name":"近两年",
                "id":5,
                "selected":false
            }
        ],
        "notRecencyUsage":[
            {
                "name":"当月",
                "id":1,
                "selected":false
            },{
                "name":"近三个月",
                "id":2,
                "selected":false
            },{
                "name":"近半年",
                "id":3,
                "selected":false
            },{
                "name":"近一年",
                "id":4,
                "selected":false
            },{
                "name":"近两年",
                "id":5,
                "selected":false
            }
        ],
        "serviceCount":[
            {
                "name":"未知",
                "id":1,
                "selected":false
            },{
                "name":"0次",
                "id":2,
                "selected":false
            },{
                "name":"1次",
                "id":3,
                "selected":false
            },{
                "name":"2次",
                "id":4,
                "selected":false
            },{
                "name":"3次",
                "id":5,
                "selected":false
            },{
                "name":"4次",
                "id":6,
                "selected":false
            },{
                "name":"5次",
                "id":7,
                "selected":false
            },{
                "name":"6-9次",
                "id":8,
                "selected":false
            },{
                "name":"10次以上",
                "id":9,
            }
        ]   
    },
    "vvip_feature_tags":{
        // "vvip_type":[
        //     {
        //         "name":"候检区",
        //         "id":1,
        //         "selected":false
        //     },{
        //         "name":"会员区",
        //         "id":2,
        //         "selected":false
        //     },{
        //         "name":"别院区",
        //         "id":3,
        //         "selected":false
        //     },{
        //         "name":"6号厅",
        //         "id":4,
        //         "selected":false
        //     },{
        //         "name":"招行厅",
        //         "id":5,
        //         "selected":false
        //     },{
        //         "name":"农行厅",
        //         "id":6,
        //         "selected":false
        //     },{
        //         "name":"工行厅",
        //         "id":7,
        //         "selected":false
        //     },{
        //         "name":"政要厅",
        //         "id":8,
        //         "selected":false
        //     }
        // ],
        "accumulationUsage":[
            {
                "name":"未知",
                "id":1,
                "selected":false
            },{
                "name":"0次",
                "id":2,
                "selected":false
            },{
                "name":"1次",
                "id":3,
                "selected":false
            },{
                "name":"2次",
                "id":4,
                "selected":false
            },{
                "name":"3次",
                "id":5,
                "selected":false
            },{
                "name":"4次",
                "id":6,
                "selected":false
            },{
                "name":"5次",
                "id":7,
                "selected":false
            },{
                "name":"6-9次",
                "id":8,
                "selected":false
            },{
                "name":"10-19次",
                "id":9,
                "selected":false
            },{
                "name":"20-29次",
                "id":10,
                "selected":false
            },{
                "name":"30次及以上",
                "id":11,
                "selected":false
            }
        ],
        "recencyUsage":[
            {
                "name":"当月",
                "id":1,
                "selected":false
            },{
                "name":"近三个月",
                "id":2,
                "selected":false
            },{
                "name":"近半年",
                "id":3,
                "selected":false
            },{
                "name":"近一年",
                "id":4,
                "selected":false
            },{
                "name":"近两年",
                "id":5,
                "selected":false
            }
        ],
        "notRecencyUsage":[
            {
                "name":"当月",
                "id":1,
                "selected":false
            },{
                "name":"近三个月",
                "id":2,
                "selected":false
            },{
                "name":"近半年",
                "id":3,
                "selected":false
            },{
                "name":"近一年",
                "id":4,
                "selected":false
            },{
                "name":"近两年",
                "id":5,
                "selected":false
            }
        ],
        "serviceCount":[
            {
                "name":"未知",
                "id":1,
                "selected":false
            },{
                "name":"0次",
                "id":2,
                "selected":false
            },{
                "name":"1次",
                "id":3,
                "selected":false
            },{
                "name":"2次",
                "id":4,
                "selected":false
            },{
                "name":"3次",
                "id":5,
                "selected":false
            },{
                "name":"4次",
                "id":6,
                "selected":false
            },{
                "name":"5次",
                "id":7,
                "selected":false
            },{
                "name":"6-9次",
                "id":8,
                "selected":false
            },{
                "name":"10次以上",
                "id":9,
            }
        ]   
    }
}

